#! /usr/bin/env php

<?php 

use Symfony\Component\Console\Application;
use Acme\WhatIsYourName;

require 'vendor/autoload.php';

$app = new Application('ConsoleAppDemo', '1.0');

$app->add(new WhatIsYourName);

$app->run();
